pool:
  vmImage: 'ubuntu-latest'

variables:
  friendlyTag: 'next'
  nodeVersion: 'unknown'
  yarnVersion: 'unknown'
  previewModifier: '-preview'

trigger:
  - main

steps:
  - script: echo "##vso[task.setvariable variable=nodeVersion]$(awk '/ENV NODE_VERSION/ { print $3 }' Dockerfile)"
    displayName: 'Set nodeVersion'

  - script: echo "##vso[task.setvariable variable=yarnVersion]$(awk '/ENV YARN_VERSION/ { print $3 }' Dockerfile)"
    displayName: 'Set yarnVersion'

  - script: echo '##vso[task.setvariable variable=buildVersion]latest'
    displayName: "Set the friendlyTag as 'latest' if the Build.SourceBranch = 'refs/heads/main' "
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  - script: echo '##vso[task.setvariable variable=previewModifier]'
    displayName: "Clear '-preview' modifier if the Build.SourceBranch = 'refs/heads/main' "
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: dockerHubRegistryServiceConnection
  - task: Docker@2
    displayName: Build and push the image
    inputs:
      command: buildAndPush
      repository: rentpath/rp_node_alpine
      tags: |
        $(Build.BuildId)
        $(friendlyTag)
        node-v$(nodeVersion)_yarn-v$(yarnVersion)$(previewModifier)
